eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      override.system-properties: false

# Product Service URL
product:
  service:
    url: http://localhost:9191

# Cart Service URL
cart:
  service:
    url: http://localhost:9292

# Order Service URL
order:
  service:
    url: http://localhost:9393