spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peerislands?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: peerislands
    password: peerislands_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9393